
stages:          
  - machine-setup
  - build
  - test

install-dotnet:
  stage: machine-setup
  script:
    - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"    
    - brew install wget
    - wget https://dot.net/v1/dotnet-install.sh
    - chmod +x dotnet-install.sh
    - ./dotnet-install.sh

install-snyk:
  stage: machine-setup
  needs:
    - install-dotnet
  script:
    - brew

build-job:
  stage: build
  needs:
    - install-dotnet
  script:
    - dotnet build

unit-test-job:
  stage: test   
  needs:
  - install-dotnet
  script:
    - dotnet test

snyk-code-review-job:
  stage: test 
  needs:
    - install-snyk
  script:
    - brew
    - npm
